# Generated by Django 5.2 on 2025-05-04 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=50, unique=True, verbose_name='Инвентарный номер')),
                ('serial_number', models.CharField(blank=True, max_length=50, verbose_name='Серийный номер')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.device', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'Экземпляр',
                'verbose_name_plural': 'Экземпляры',
                'ordering': ['inventory_number'],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item', verbose_name='Экземпляр')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.location', verbose_name='Расположение')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.responsible', verbose_name='Ответственный')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.status', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Эксплуатация',
                'verbose_name_plural': 'Эксплуатация',
                'ordering': ['-updated_at'],
            },
        ),
    ]
