# Generated by Django 5.2.1 on 2025-05-18 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.device', verbose_name='Устройство'),
        ),
    ]
