# Generated by Django 5.2.1 on 2025-05-18 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_alter_location_options_alter_responsible_options_and_more'),
        ('devices', '0003_alter_category_options_alter_device_options_and_more'),
        ('inventory', '0002_alter_item_created_at_alter_item_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['inventory_number'], 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='operation',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Operation', 'verbose_name_plural': 'Operations'},
        ),
        migrations.AlterField(
            model_name='item',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.device', verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='item',
            name='inventory_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Inventory number'),
        ),
        migrations.AlterField(
            model_name='item',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Serial number'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.responsible', verbose_name='Responsible'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.status', verbose_name='Status'),
        ),
    ]
