# Generated by Django 5.2.13 on 2026-04-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0003_alter_location_options_alter_responsible_options_and_more"),
        ("inventory", "0003_alter_item_options_alter_operation_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="operation",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "Operation",
                "verbose_name_plural": "Operations",
            },
        ),
        migrations.AddIndex(
            model_name="operation",
            index=models.Index(
                fields=["item", "-created_at", "-id"],
                name="inventory_op_item_latest_idx",
            ),
        ),
    ]
