# Generated by Django 5.2.13 on 2026-04-30 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0004_alter_location_options_alter_status_options"),
        ("inventory", "0004_alter_operation_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional. Transfers are ignored after expiration.",
                        null=True,
                        verbose_name="Expires at",
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Accepted at"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Cancelled at"
                    ),
                ),
                (
                    "from_responsible",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_transfers",
                        to="catalogs.responsible",
                        verbose_name="From",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.item",
                        verbose_name="Item",
                    ),
                ),
                (
                    "to_responsible",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_transfers",
                        to="catalogs.responsible",
                        verbose_name="To",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pending transfer",
                "verbose_name_plural": "Pending transfers",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=[
                            "item",
                            "accepted_at",
                            "cancelled_at",
                            "-created_at",
                            "-id",
                        ],
                        name="inv_pend_xfer_item_idx",
                    )
                ],
            },
        ),
    ]
