# Generated by Django 5.2.13 on 2026-05-02 12:10
#
# Supports inventory list query plans; see docs/inventory-list-query-profiling.md.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0004_alter_location_options_alter_status_options"),
        ("inventory", "0005_pendingtransfer"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="operation",
            index=models.Index(
                fields=["responsible", "item", "-created_at", "-id"],
                name="inventory_op_resp_item_idx",
            ),
        ),
    ]
