# Generated by Django 5.2.13 on 2026-05-08 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0004_alter_location_options_alter_status_options"),
        ("inventory", "0006_operation_inventory_op_resp_item_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.item",
                verbose_name="Item",
            ),
        ),
        migrations.AddIndex(
            model_name="pendingtransfer",
            index=models.Index(
                fields=["from_responsible", "accepted_at", "cancelled_at"],
                name="inv_pend_xfer_from_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pendingtransfer",
            index=models.Index(
                fields=["to_responsible", "accepted_at", "cancelled_at"],
                name="inv_pend_xfer_to_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pendingtransfer",
            index=models.Index(fields=["expires_at"], name="inv_pend_xfer_expires_idx"),
        ),
    ]
