# Generated by Django 5.2.13 on 2026-06-02 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_alter_operation_item_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingtransfer",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.item",
                verbose_name="Item",
            ),
        ),
    ]
