# Generated by Django 5.2 on 2025-05-03 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('category', 'manufacturer', 'model')},
        ),
    ]
