# Generated by Django 5.2 on 2025-05-03 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255, unique=True, verbose_name='Серийный номер')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.model', verbose_name='Модель')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.vendor', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
                'ordering': ['vendor', 'model', 'serial_number'],
            },
        ),
    ]
