# Generated by Django 5.2.1 on 2025-05-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_alter_location_options_alter_status_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsible',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество'),
        ),
    ]
