# Generated by Django 5.2.1 on 2025-05-18 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_alter_responsible_middle_name'),
        ('inventory', '0002_alter_item_device'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
