# Generated by Django 5.2.13 on 2026-04-30 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0003_alter_location_options_alter_responsible_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={
                "ordering": ["name"],
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
            },
        ),
        migrations.AlterModelOptions(
            name="status",
            options={
                "ordering": ["name"],
                "verbose_name": "Status",
                "verbose_name_plural": "Statuses",
            },
        ),
    ]
