# Generated by Django 5.2.14 on 2026-05-29 14:12

import django.db.models.deletion
from django.db import migrations, models


def ensure_global_on_hand(apps, _schema_editor):  # pragma: no cover
    Location = apps.get_model("catalogs", "Location")

    on_hand = (
        Location.objects.filter(responsible__isnull=True, name="on_hand")
        .order_by("pk")
        .first()
    )
    russian_on_hand = (
        Location.objects.filter(responsible__isnull=True, name="На руках")
        .order_by("pk")
        .first()
    )

    if on_hand is None and russian_on_hand is not None:
        russian_on_hand.name = "on_hand"
        russian_on_hand.save(update_fields=["name"])
        on_hand = russian_on_hand

    if on_hand is None:
        Location.objects.create(name="on_hand")

    duplicate_queryset = Location.objects.filter(
        responsible__isnull=True, name="На руках"
    )
    for index, duplicate in enumerate(duplicate_queryset.order_by("pk"), start=1):
        duplicate.name = f"На руках {duplicate.pk or index}"
        duplicate.save(update_fields=["name"])


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0004_alter_location_options_alter_status_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="responsible",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="locations",
                to="catalogs.responsible",
                verbose_name="Responsible",
            ),
        ),
        migrations.RunPython(ensure_global_on_hand, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                condition=models.Q(("responsible__isnull", True)),
                fields=("name",),
                name="catalogs_location_unique_global_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                condition=models.Q(("responsible__isnull", False)),
                fields=("responsible", "name"),
                name="catalogs_location_unique_responsible_name",
            ),
        ),
    ]
