# Generated by OpenCode on 2026-05-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0005_location_responsible_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
    ]
