"""
Django settings for sloths_inventory project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import environ

env = environ.Env()
# reading .env file
environ.Env.read_env()


def _env_int(name: str, default: int) -> int:
    v = os.environ.get(name, "").strip()
    return int(v) if v else default


def _env_float(name: str, default: float) -> float:
    v = os.environ.get(name, "").strip()
    return float(v) if v else default


def _env_bool(name: str, default: bool) -> bool:
    v = os.environ.get(name, "").strip().lower()
    if not v:
        return default
    return v in ("true", "1", "yes", "on")


def _split_env_list(raw: str) -> list[str]:
    return [part.strip() for part in raw.split(",") if part.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DEBUG", default=False)

# DEBUG flag
if DEBUG:
    SECRET_KEY = env.str("SECRET_KEY", default="unsafe-secret-key")
else:
    SECRET_KEY = env.str("SECRET_KEY")

SECURE_SSL_REDIRECT = _env_bool("SECURE_SSL_REDIRECT", default=not DEBUG)
SESSION_COOKIE_SECURE = _env_bool("SESSION_COOKIE_SECURE", default=not DEBUG)
CSRF_COOKIE_SECURE = _env_bool("CSRF_COOKIE_SECURE", default=not DEBUG)

_secure_proxy_ssl_header_name = os.environ.get(
    "SECURE_PROXY_SSL_HEADER_NAME", ""
).strip()
_secure_proxy_ssl_header_value = os.environ.get(
    "SECURE_PROXY_SSL_HEADER_VALUE", ""
).strip()
if _secure_proxy_ssl_header_name and _secure_proxy_ssl_header_value:
    SECURE_PROXY_SSL_HEADER = (
        _secure_proxy_ssl_header_name,
        _secure_proxy_ssl_header_value,
    )

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

#
ALLOWED_HOSTS = _split_env_list(env.str("ALLOWED_HOSTS", default=""))
CSRF_TRUSTED_ORIGINS = _split_env_list(env.str("CSRF_TRUSTED_ORIGINS", default=""))

# Inventory domain settings
#
# The inventory state is derived from an append-only stream of `Operation` records.
# We allow editing only the latest operation, and only for a short period of time
# after it was created, to fix quick typos without rewriting history "after the fact".
# The same minute cap applies to ``Item`` rows using each row's ``created_at`` as
# the anchor once the item has at least one ``Operation`` (see ``Item.clean()``),
# and to catalog / device definition rows once referenced (see
# ``common.catalog_correction_window.CatalogCorrectionWindowMixin``). Django superusers
# bypass that correction window in the admin only (``ItemAdmin`` and catalog admins).
# The window is intentionally small by default and can be tuned per deployment.
#
# Note: The correction window is anchored on ``created_at`` (immutable timestamp),
# not ``updated_at``, so the window does not reset on each save.
INVENTORY_CORRECTION_WINDOW_MINUTES = _env_int(
    "INVENTORY_CORRECTION_WINDOW_MINUTES", default=0
)

# Pending transfer offers created from the user UI get `expires_at` set to
# "now + N hours" when N > 0. Zero disables automatic expiry (offers do not expire
# unless set manually in the admin).
INVENTORY_PENDING_TRANSFER_EXPIRATION_HOURS = _env_int(
    "INVENTORY_PENDING_TRANSFER_EXPIRATION_HOURS", default=168
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "dal",
    "dal_select2",
    "common",
    "devices",
    "catalogs",
    "inventory",
    "health",
    "django_q",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "common.timezone.TimezoneMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "sloths_inventory.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "common.timezone.timezone_context",
                "common.notifications.persistent_notifications",
            ],
        },
    },
]

WSGI_APPLICATION = "sloths_inventory.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env.str("DATABASE_NAME", default=""),
        "USER": env.str("DATABASE_USER", default=""),
        "PASSWORD": env.str("DATABASE_PASSWORD", default=""),
        "HOST": env.str("DATABASE_HOST", default=""),
        "PORT": _env_int("DATABASE_PORT", default=5432),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Time
USE_TZ = True

TIME_ZONE = env.str("TIME_ZONE", default="UTC")

# Internationalization
# https://docs.djangoprojectP.com/en/5.2/topics/i18n/

USE_I18N = True

LANGUAGES = [
    ("en", "English"),
    ("ru", "Русский"),
]

LOCALE_PATHS = [
    BASE_DIR / "common" / "locale",
    BASE_DIR / "devices" / "locale",
    BASE_DIR / "catalogs" / "locale",
    BASE_DIR / "inventory" / "locale",
    BASE_DIR / "health" / "locale",
]

# Language selection settings
LANGUAGE_COOKIE_NAME = "django_language"
LANGUAGE_COOKIE_AGE = None
LANGUAGE_COOKIE_DOMAIN = None
LANGUAGE_COOKIE_PATH = "/"

LANGUAGE_CODE = "en"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Test runner
TEST_RUNNER = "sloths_inventory.tests.runner.PytestTestRunner"

# Login
LOGIN_URL = "common:login"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# Email configuration
# https://docs.djangoproject.com/en/5.2/topics/email/

EMAIL_BACKEND = env.str(
    "EMAIL_BACKEND", default="common.email_backends.AsyncEmailBackend"
)
EMAIL_HOST = env.str("EMAIL_HOST", default="")
EMAIL_PORT = _env_int("EMAIL_PORT", default=587)
EMAIL_USE_TLS = _env_bool("EMAIL_USE_TLS", default=True)
EMAIL_USE_SSL = _env_bool("EMAIL_USE_SSL", default=False)
EMAIL_HOST_USER = env.str("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env.str("EMAIL_HOST_PASSWORD", default="")
EMAIL_TIMEOUT = _env_int("EMAIL_TIMEOUT", default=10)

DEFAULT_FROM_EMAIL = env.str("DEFAULT_FROM_EMAIL", default="noreply@example.com")
SERVER_EMAIL = env.str("SERVER_EMAIL", default="noreply@example.com")

EMAIL_SEND_ASYNC = _env_bool("EMAIL_SEND_ASYNC", default=True)
EMAIL_RETRY_MAX_RETRIES = _env_int("EMAIL_RETRY_MAX_RETRIES", default=2)
EMAIL_RETRY_BASE_DELAY_SECONDS = _env_float(
    "EMAIL_RETRY_BASE_DELAY_SECONDS", default=60.0
)
EMAIL_RETRY_BACKOFF_FACTOR = _env_float("EMAIL_RETRY_BACKOFF_FACTOR", default=2.0)

# django-q2 task queue — PostgreSQL ORM broker (no Redis required)
Q_CLUSTER = {
    "name": env.str("Q_CLUSTER_NAME", default="sloths_inventory"),
    "workers": _env_int("Q_WORKERS", default=1),
    "timeout": _env_int("Q_TIMEOUT", default=60),
    "retry": _env_int("Q_RETRY", default=120),
    "orm": "default",
    "sync": not _env_bool("Q_ASYNC", default=True),
}

# Site URL for email links (required for password reset emails)
SITE_URL = env.str("SITE_URL", default="")

# Password reset token expiration (Django default is 3 days)
PASSWORD_RESET_TIMEOUT = 60 * 60 * 24 * 3  # 3 days in seconds

# Logging
LOG_LEVEL = env.str("LOG_LEVEL", default="DEBUG" if DEBUG else "INFO")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "default": {
            "format": "%(asctime)s %(levelname)s %(name)s %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "default",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        # Keep Django's request errors visible and avoid double-propagation surprises.
        "django.request": {"level": "ERROR", "propagate": True},
    },
}

if SECURE_SSL_REDIRECT:
    SECURE_REDIRECT_EXEMPT = [r"^health/"]
