"""
Django settings for sloths_inventory project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import environ
from django.core.exceptions import ImproperlyConfigured

env = environ.Env()
# reading .env file
environ.Env.read_env()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

# SECURITY WARNING: keep the secret key used in production secret!
#
# In non-debug environments the key must be explicitly provided via env vars.
if DEBUG:
    SECRET_KEY = env("SECRET_KEY", default="unsafe-secret-key")
else:
    SECRET_KEY = env("SECRET_KEY", default=None)
    if not SECRET_KEY:
        raise ImproperlyConfigured("SECRET_KEY must be set when DEBUG is False")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _split_env_list(raw: str) -> list[str]:
    return [part.strip() for part in raw.split(",") if part.strip()]


ALLOWED_HOSTS = _split_env_list(env("ALLOWED_HOSTS", default=""))

CSRF_TRUSTED_ORIGINS = _split_env_list(env("CSRF_TRUSTED_ORIGINS", default=""))

# Inventory domain settings
#
# The inventory state is derived from an append-only stream of `Operation` records.
# We allow editing only the latest operation, and only for a short period of time
# after it was created, to fix quick typos without rewriting history "after the fact".
# The same minute cap applies to ``Item`` rows using each row's previous
# ``updated_at`` as the anchor once the item has at least one ``Operation`` (see
# ``Item.clean()``), and to catalog / device definition rows once referenced (see
# ``common.catalog_correction_window.CatalogCorrectionWindowMixin``). Django superusers
# bypass that correction window in the admin only (``ItemAdmin`` and catalog admins).
# The window is intentionally small by default and can be tuned per deployment.
INVENTORY_CORRECTION_WINDOW_MINUTES = env.int(
    "INVENTORY_CORRECTION_WINDOW_MINUTES",
    default=10,
)

# Pending transfer offers created from the user UI get `expires_at` set to
# "now + N hours" when N > 0. Zero disables automatic expiry (offers do not expire
# unless set manually in the admin).
INVENTORY_PENDING_TRANSFER_EXPIRATION_HOURS = env.int(
    "INVENTORY_PENDING_TRANSFER_EXPIRATION_HOURS",
    default=168,
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "common",
    "devices",
    "catalogs",
    "inventory",
    "health",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "sloths_inventory.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "sloths_inventory.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("DATABASE_NAME", default="database"),
        "USER": env("DATABASE_USER", default="user"),
        "PASSWORD": env("DATABASE_PASSWORD", default="password"),
        "HOST": env("DATABASE_HOST", default="127.0.0.1"),
        "PORT": env("DATABASE_PORT", default="5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en"

TIME_ZONE = env.str("TIME_ZONE", default="UTC")

USE_I18N = True
USE_TZ = True

LANGUAGES = [
    ("en", "English"),
    ("ru", "Русский"),
]

LOCALE_PATHS = [
    BASE_DIR / "common" / "locale",
    BASE_DIR / "devices" / "locale",
    BASE_DIR / "catalogs" / "locale",
    BASE_DIR / "inventory" / "locale",
    BASE_DIR / "health" / "locale",
]

# Language selection settings
LANGUAGE_COOKIE_NAME = "django_language"
LANGUAGE_COOKIE_AGE = None
LANGUAGE_COOKIE_DOMAIN = None
LANGUAGE_COOKIE_PATH = "/"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Test runner
TEST_RUNNER = "sloths_inventory.tests.runner.PytestTestRunner"

LOGIN_URL = "common:login"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# Logging
LOG_LEVEL = env("LOG_LEVEL", default="DEBUG" if DEBUG else "INFO")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "default": {
            "format": "%(asctime)s %(levelname)s %(name)s %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "default",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        # Keep Django's request errors visible and avoid double-propagation surprises.
        "django.request": {"level": "ERROR", "propagate": True},
    },
}
