# Generated by Django 5.2.1 on 2025-05-18 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_category_options_alter_manufacturer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.category', verbose_name='Категория')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.manufacturer', verbose_name='Производитель')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.model', verbose_name='Модель')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.type', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
                'ordering': ['category', 'type', 'manufacturer', 'model'],
                'unique_together': {('category', 'type', 'manufacturer', 'model')},
            },
        ),
    ]
