# Generated by Django 5.2.13 on 2026-04-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0003_alter_category_options_alter_device_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="device",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.UniqueConstraint(
                fields=("category", "type", "manufacturer", "model"),
                name="devices_device_cat_type_mfr_model_uniq",
            ),
        ),
    ]
